<?php
session_start();
include('./inc/config.php');
include('./inc/functions.php');


if (empty($_SESSION['uid'])) {
    header("Location: index.php");
    exit;
}
$userClass = new userClass();
$userDetails = $userClass->userDetails($_SESSION['uid']);
$secret = $userDetails->google_auth_code;
$email = $userDetails->email;

$ga = new GoogleAuthenticator();

$qrCodeUrl = $ga->getQRCodeGoogleUrl($email, $secret, 'LonoxX_2FA_Demo');

$verificationError = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $code = $_POST['code'];
    $isCodeValid = $ga->verifyCode($secret, $code, 1); // 1 = 1*30sec clock tolerance

    if ($isCodeValid) {
        header("Location: home.php");
        exit;
    } else {
        $verificationError = "Invalid code. Please try again.";
    }
}
?>

<!DOCTYPE html>
<html>

<head>
    <title>2-Step Verification using Google Authenticator</title>
    <link rel="stylesheet" type="text/css" href="style.css" charset="utf-8" />
</head>

<body>
    <div id="container">
        <h1>2-Step Verification using Google Authenticator</h1>
        <div id='device'>
            <p>Enter the verification code generated by Google Authenticator app on your phone.</p>
            <div id="img">
                <img src='<?php echo $qrCodeUrl; ?>' alt="QR Code" />
            </div>
            <form method="post" action="home.php">
                <label>Enter Google Authenticator Code</label>
                <input type="text" name="code" />
                <input type="submit" class="button" />
                <p class="error"><?php echo $verificationError; ?></p>
            </form>
        </div>
    </div>
</body>

</html>
